[theme]
primaryColor = "#3d3c35"
# backgroundColor = "#10344b"
backgroundColor = "#2b2b4d"
# secondaryBackgroundColor = "#154360"
secondaryBackgroundColor = "#1f1f33"
textColor = "#C3C3C3"
font = "sans serif"

[server]
enableStaticServing = true