[theme]
primaryColor = "#A1F7B4"
# backgroundColor = "#10344b"
backgroundColor = "#e8dcd4"
# secondaryBackgroundColor = "#154360"
secondaryBackgroundColor = "#e8dcd4"
textColor = "#3d3c35"
font = "sans serif"

[server]
enableStaticServing = true