[theme]
primaryColor = "#A1F7B4"
# backgroundColor = "#10344b"
backgroundColor = "#FFFFFF"
# secondaryBackgroundColor = "#154360"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
enableStaticServing = true