[theme]
primaryColor = "#A1F7B4"
# backgroundColor = "#10344b"
backgroundColor = "#CFBE88"
# secondaryBackgroundColor = "#154360"
secondaryBackgroundColor = "#CFBE88"
textColor = "#1F1E1D"
font = "sans serif"

[server]
enableStaticServing = true